## Configuration principale pour HTC-DC-Net sur BatimentsMaroc
model: htcdc
backbone: efficientnetb0
project: BatimentsMaroc

## Data configuration
data_dir: ../../../data/htc_dc_net_format
data_split_dirs: ../../../data/htc_dc_net_format/splits
batch_size: 8
num_workers: 4
image_size: 256
crop: null
use_mask: True
normalize: True

## Training configuration
max_epochs: 200
lr: 0.0001
chamfer_weight: 0.01
log_interval: 50
checkpoint_interval: 10
patience: 30

optimizer: AdamW

device: cuda

early_stopping: ['mae', 'rmse', 'val/loss_total']
early_stopping_mode: ['min', 'min', 'min']
